import added
trngl8/library-project pull request #152
Opened 2023-08-01 10:00 UTC by ArtemKrayevskiy

2023-08-01 10:13 UTC, roman-duck commented
Manual test result:
```
FileNotFoundError: [Errno 2] No such file or directory: 'var/import/books.csv'
```

2023-08-01 11:02 UTC, roman-duck commented
@ArtemKrayevskiy when I created 'var/import' manually, the exception has gone.
When uploading and saving to the storage is successful (or not), the result flash message on the 'index' page should be shown

2023-08-01 17:07 UTC, roman-duck commented on templates/index.html
> +      <form action="#" method="post" enctype="multipart/form-data">
action="#" may be removed

2023-08-01 17:16 UTC, mvchn commented on index.py
> +            import_service = FileImport()
I woluld like to use import like this:
```
import_service = FileImport(app.config['UPLOAD_FOLDER'])
import_service.process_file(file, filename)
```
It allows us to remove **os** dependency from index.py

2023-08-01 19:00 UTC, mvchn requested changes
It is better to append (not to rewrite) data in the storage.
The ID field in the storage should be an auto-increment value.

2023-08-03 17:14 UTC, roman-duck commented on file.py
> +                file.write(str(i.id) + "," + i.title + ',' + i.author + ',' + str(i.year) + '\n')
no new line at the end of the file

2023-08-07 10:25 UTC, roman-duck commented
On uploading a new file with books data a message shows:

"Your file was imported successfully. 9 unique books imported"

**Actual result:**
Imported books are not present on the index page

**Expected result:**
Imported books are present on the index page

2023-08-07 10:39 UTC, roman-duck commented on file.py
> +            print(file_containment)
looks like debug print

2023-08-07 11:25 UTC, ArtemKrayevskiy commented
Can I save the imported file in var/import and copy the containment to the books.csv in var/data?

2023-08-07 12:14 UTC, roman-duck commented
of course, you can

Here is a sample from the original issue:

`system should save the file to the /var/import directory, parse it, and save parsed data to the storage.`

2023-08-07 13:44 UTC, roman-duck approved these changes

2023-08-07 13:46 UTC, mvchn approved these changes

2023-08-07 15:21 UTC, merged