change name added, close #164
trngl8/library-project pull request #215
Opened 2023-08-21 11:09 UTC by ArtemKrayevskiy

2023-08-21 11:26 UTC, roman-duck requested changes
form should be defined as form object

2023-08-21 11:30 UTC, roman-duck requested changes
On the original issue form should be on the settings page, not profile

2023-08-21 11:30 UTC, roman-duck requested changes

2023-08-21 11:30 UTC, webdewduck commented on templates/profile.html
> +{% if messages %}
unexpected flash messages duplicates

2023-08-22 15:04 UTC, mvchn commented on index.py
> +        if not re.match(r"[A-Za-z0-9_-]+", username):
looks like a validation after form.validate()

2023-08-22 16:22 UTC, roman-duck approved these changes

2023-08-22 16:22 UTC, merged