Issues/24
trngl8/library-project pull request #58
Opened 2023-07-03 08:16 UTC by ArtemKrayevskiy

2023-07-03 11:29 UTC, mvchn commented on main.py
> +from library import *
It will be better to import dependencies separately

2023-07-03 11:30 UTC, mvchn commented on main.py
> +    for i in library.catalog:
some duplicates as line 23

2023-07-03 11:35 UTC, mvchn requested changes
Commit https://github.com/trngl8/library-project/pull/58/commits/4213e95cf2ac5d9ab01aada9382e43ac11b8f7c3 should be removed from the branch

2023-07-04 16:01 UTC, roman-duck commented on library.py
> +        return f"Book {self.title} ritten by {self.author} in {self.year}"
maybe "written" or other verb

2023-07-04 16:02 UTC, roman-duck approved these changes
function find_book has duplicates and should be refactored

2023-07-04 16:09 UTC, mvchn approved these changes

2023-07-04 16:10 UTC, merged